import assert from 'node:assert/strict';
export async function testCareer(request,db,a,b,c){
 await request('/api/career',{status:401});await request('/api/skill-beacons',{status:401});
 const before=(await request('/api/career',{cookie:a})).data;
 assert.equal(before.tracks.length,4);assert.equal(before.opportunities.length,3);assert.equal(before.questions.length,3);
 assert.ok(before.opportunities.every(o=>o.match===0));assert.ok(before.tracks.every(t=>t.completed.length===0));
 const profile={...before.profile,skills:['React','Tailwind CSS'],resume:'I build React interfaces and use Tailwind CSS with accessible HTML. My projects demonstrate tested UI components.',targetRole:'Frontend Developer'};
 const post=(cookie,body,status=200)=>request('/api/career',{cookie,method:'POST',body,status});
 await post(a,{action:'profile',profile,version:-1});await post(a,{action:'profile',profile,version:-1},409);
 assert.deepEqual((await request('/api/career',{cookie:b})).data.profile.skills,[]);
 const updated=(await request('/api/career',{cookie:a})).data;
 const opp=updated.opportunities.find(o=>o.title==='Front-End Developer Intern');assert.equal(opp.match,67);
 await post(a,{action:'bookmark',id:opp.id,saved:true});await post(a,{action:'bookmark',id:opp.id,saved:true});
 assert.equal((await db.prepare('SELECT count(*) AS n FROM career_saved WHERE user_id=? AND opportunity_id=?').bind('demo-user-0',opp.id).first()).n,1);
 await post(a,{action:'apply',id:opp.id,note:'I would like to apply with my React projects.',consent:false},422);
 await post(a,{action:'apply',id:opp.id,note:'I would like to apply with my React projects.',consent:true});
 await post(a,{action:'apply',id:opp.id,note:'Duplicate request should not create another row.',consent:true});
 const track=updated.tracks[0];await post(a,{action:'progress',id:track.id,completed:[0],version:-1});await post(a,{action:'progress',id:track.id,completed:[1],version:-1},409);await post(a,{action:'progress',id:track.id,completed:[99],version:0},422);
 const low=(await post(a,{action:'resume-check',id:opp.id,answer:'I study geography and enjoy creating wildlife photographs.'})).data.feedback;
 const high=(await post(a,{action:'resume-check',id:opp.id,answer:'I build with React and Next.js, Tailwind CSS and Git workflows.'})).data.feedback;
 assert.equal(low.score,0);assert.equal(high.score,100);
 await post(a,{action:'interview',id:updated.questions[0].id,answer:'I render on the server to reduce the JavaScript bundle and keep secrets secure, using interactive event handlers for the client.'});
 assert.equal((await request('/api/career',{cookie:b})).data.attempts.length,0);
 const listing=(await post(a,{action:'create-opportunity',title:'Persistence test campus project',company:'Student team',type:'Project',category:'All Campus',stipend:'Peer collaboration',requirements:['JavaScript'],description:'Build a tested campus project together.'},201)).data.id;
 await post(a,{action:'apply',id:listing,note:'Cannot apply to my own opportunity.',consent:true},422);
 await post(b,{action:'apply',id:listing,note:'I can contribute JavaScript and tests.',consent:true});
 await request('/api/career?applicants='+listing,{cookie:b,status:403});
 const applicants=(await request('/api/career?applicants='+listing,{cookie:a})).data.applicants;assert.equal(applicants.length,1);
 await post(c,{action:'review-application',id:listing,userId:applicants[0].userId,status:'Accepted'},403);
 await post(a,{action:'review-application',id:listing,userId:applicants[0].userId,status:'Accepted'});
 assert.equal((await request('/api/career',{cookie:b})).data.opportunities.find(o=>o.id===listing).application,'Accepted');
 await post(a,{action:'close-opportunity',id:listing});await post(c,{action:'apply',id:listing,note:'Applying after this opportunity closed.',consent:true},409);
 const pinBody={action:'create',kind:'skill',title:'Career test code review',description:'Meet to review our JavaScript code.',location:'Central Library',room:'Room 204',reward:'Peer help',x:43,y:22,duration:45};
 const pin=(await request('/api/skill-beacons',{cookie:a,method:'POST',body:pinBody,status:201})).data.id;
 await request('/api/skill-beacons',{cookie:a,method:'POST',body:{...pinBody,x:101},status:422});
 await request('/api/skill-beacons',{cookie:b,method:'POST',body:{action:'join',id:pin}});await request('/api/skill-beacons',{cookie:b,method:'POST',body:{action:'join',id:pin}});
 const beacon=(await request('/api/skill-beacons',{cookie:a})).data.beacons.find(x=>x.id===pin);assert.equal(beacon.members,2);assert.equal(beacon.x,43);assert.equal(beacon.room,'Room 204');
 await request('/api/skill-beacons',{cookie:b,method:'POST',body:{action:'delete',id:pin},status:403});
 await db.prepare('UPDATE skill_beacons SET expires_at=? WHERE id=?').bind(Date.now()-1,pin).run();
 assert.ok(!(await request('/api/skill-beacons',{cookie:a})).data.beacons.some(x=>x.id===pin));
 await request('/api/skill-beacons',{cookie:b,method:'POST',body:{action:'join',id:pin},status:410});
 await db.prepare('UPDATE skill_beacons SET expires_at=? WHERE id=?').bind(Date.now()+45*60000,pin).run();
 console.log('Career: real match scores, private profiles, bookmarks, duplicate applications, owner review, stale progress, distinct feedback and expiring map pins passed.');
 return async()=>{
 const saved=(await request('/api/career',{cookie:a})).data;
 assert.ok(saved.opportunities.find(o=>o.id===opp.id).saved);assert.equal(saved.opportunities.find(o=>o.id===opp.id).application,'Pending');assert.deepEqual(saved.profile.skills,profile.skills);assert.deepEqual(saved.tracks.find(t=>t.id===track.id).completed,[0]);assert.ok(saved.attempts.length>=3);
 assert.ok((await request('/api/skill-beacons',{cookie:b})).data.beacons.some(x=>x.id===pin&&x.joined));console.log('Career profile, applications, saved roles, module progress, feedback and map pins survive Worker restart.');
 };
}
