import assert from 'node:assert/strict';
export async function testCareerBrowser(context,page,base){
 context.setDefaultTimeout(12000);
 await page.getByRole('button',{name:'Career tools',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByLabel('Skills, separated by commas').fill('React, Tailwind CSS');
 await dialog.getByLabel('Skills, separated by commas').press('End');
 await dialog.getByLabel('Skills, separated by commas').pressSequentially(', Git workflows',{delay:15});
 assert.equal(await dialog.getByLabel('Skills, separated by commas').inputValue(),'React, Tailwind CSS, Git workflows');
 await dialog.getByRole('button',{name:'Save skills',exact:true}).click();
 await dialog.getByRole('button',{name:'Save skills',exact:true}).waitFor();
 await dialog.getByRole('button',{name:'Roadmap',exact:true}).click();
 await dialog.getByLabel('Current CGPA (0–10)',{exact:true}).fill('8.2');
 await dialog.getByLabel('CGPA goal (0–10)',{exact:true}).fill('9');
 await dialog.getByRole('button',{name:'Save roadmap',exact:true}).click();
 await dialog.getByText('8.2 / 9',{exact:true}).waitFor();
 await dialog.getByRole('button',{name:'Resume check',exact:true}).click();
 await dialog.getByLabel('Your resume text',{exact:true}).fill('I build with React, Tailwind CSS and Git workflows. I test accessibility and database persistence in my campus projects.');
 await dialog.getByRole('button',{name:'Save resume draft',exact:true}).click();
 await dialog.getByRole('button',{name:'Check keywords',exact:true}).click();
 await dialog.getByText('Latest saved check',{exact:false}).waitFor();
 const popupPromise=context.waitForEvent('page');
 await dialog.getByRole('link',{name:'Print / save PDF',exact:true}).click();
 const resume=await popupPromise;await resume.waitForLoadState();await resume.getByText('I build with React, Tailwind CSS and Git workflows.',{exact:false}).waitFor();
 await resume.close();
 await dialog.getByRole('button',{name:'Close career tools',exact:true}).click();
 await page.getByRole('button',{name:'Campus',exact:true}).click();
 await page.getByRole('button',{name:'+ Drop pin',exact:true}).click();
 const pinDialog=page.getByRole('dialog');
 await pinDialog.getByLabel('Title',{exact:true}).fill('UI test study pin');
 await pinDialog.getByLabel('Campus location',{exact:true}).selectOption('1');
 await pinDialog.getByLabel('Room / meeting point',{exact:true}).fill('204');
 await pinDialog.getByRole('button',{name:'Place pin on map',exact:true}).click();
 await page.getByRole('dialog').getByRole('heading',{name:'UI test study pin',exact:true}).waitFor();
 await page.getByRole('dialog').getByRole('button',{name:'Show meeting point',exact:true}).click();
 const marker=page.getByRole('button',{name:'Open 2 pins at Central Library',exact:true});await marker.waitFor();
 await marker.click();await page.getByRole('dialog').getByLabel('Pins at this location',{exact:true}).selectOption({label:'UI test study pin'});
 await page.getByRole('dialog').getByRole('heading',{name:'UI test study pin',exact:true}).waitFor();
 await page.getByRole('dialog').getByRole('button',{name:'Close pin details',exact:true}).click();
 await page.getByTitle('Zoom In',{exact:true}).click();await page.getByTitle('Zoom Out',{exact:true}).click();
 assert.ok((await page.getByTitle('Recenter',{exact:true}).innerText()).includes('100%'),'Zoom in and out must return to the original scale');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile page must not overflow horizontally');
 await page.getByRole('button',{name:'Home',exact:true}).click();
 await page.getByRole('button',{name:'Career tools',exact:true}).waitFor();
 await page.screenshot({path:'/workspace/scratch/aec6b105e479/qa-pastel-mobile.png'});
 await page.setViewportSize({width:1280,height:900});
 await page.getByRole('button',{name:'Home',exact:true}).waitFor();
 assert.ok((await page.locator('.phone-frame').boundingBox()).width<=421,'Desktop keeps phone width');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Desktop page must not overflow horizontally');
 await page.screenshot({path:'/workspace/scratch/aec6b105e479/qa-pastel-desktop.png'});
 await page.getByRole('button',{name:'Buddies',exact:true}).click();
 await page.getByRole('button',{name:/Academics/}).first().click();
 await page.getByRole('button',{name:/Career & Skills/}).click();
 await page.getByRole('heading',{name:'Career & Skills',exact:true}).waitFor();
 await page.getByRole('button',{name:'Home',exact:true}).click();
 console.log('Browser: stable modal typing, skills, roadmap, saved resume/print page, assessments, persisted map pin, zoom controls and mobile/desktop layout passed.');
}
