import {Miniflare} from 'miniflare';
import {testCareer} from './career.mjs';
import {testCareerBrowser} from './career-browser.mjs';
import {readFileSync,readdirSync,mkdtempSync} from 'node:fs';
import {resolve} from 'node:path';
import {tmpdir} from 'node:os';
import assert from 'node:assert/strict';
const state=mkdtempSync(resolve(tmpdir(),'lpu-db-test-'));
const options={host:'127.0.0.1',port:0,modules:[{type:'ESModule',path:resolve('dist/server/index.js')},...readdirSync('dist/server',{recursive:true}).filter(f=>f.endsWith('.js')&&f!=='index.js').map(f=>({type:'ESModule',path:resolve('dist/server',f)}))],modulesRoot:resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],cf:false,d1Databases:['DB'],d1Persist:state+'/d1',r2Buckets:['BUCKET'],r2Persist:state+'/r2',bindings:{DEMO_MODE:'true',OTP_SIGNING_SECRET:'automated-test-secret-not-for-production'},assets:{directory:resolve('dist/client'),binding:'ASSETS',routerConfig:{has_user_worker:true}}};
let mf=new Miniflare(options);
async function request(path,{cookie='',method='GET',body,status=200}={}){const r=await mf.dispatchFetch('http://localhost'+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const txt=await r.text();let data;try{data=JSON.parse(txt);}catch{throw new Error(path+': '+r.status+' '+txt.slice(0,200));}assert.equal(r.status,status,path+' '+JSON.stringify(data));return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
try{
 const db=await mf.getD1Database('DB');
 for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()){const statements=readFileSync('drizzle/'+f,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean);await db.batch(statements.map(s=>db.prepare(s)));}
 console.log('Migrations applied');
 const demos=(await request('/api/auth')).data.demoUsers;assert.ok(demos.length>=3);
 const login=async(id)=>(await request('/api/auth',{method:'POST',body:{action:'demo-login',userId:id}})).cookie;
 let a=await login(demos[0].id),b=await login(demos[1].id),c=await login(demos[2].id);
 console.log('Three accounts authenticated');
 const passwordLogin=async(email,password,status=200)=>request('/api/auth',{method:'POST',status,body:{action:'password-login',email,password}});
 const signed=await passwordLogin('student0@demo.campus.ac.in','QuadDemo!2026');assert.ok(signed.cookie);assert.equal(signed.data.user.id,'demo-user-0');
 await passwordLogin('student0@demo.campus.ac.in','wrong-password',401);
 await request('/api/directory',{status:401});
 const directory=(await request('/api/directory',{cookie:a})).data;
 assert.equal(directory.members.length,13);assert.equal(directory.counts.total,13);assert.equal(directory.counts.buddies,12);assert.equal(directory.counts.food,10);assert.equal(directory.counts.vendors,11);
 assert.equal((await request('/api/buddies',{cookie:a})).data.buddies.length,directory.counts.buddies);
 assert.deepEqual((await request('/api/home',{cookie:a})).data.pulse,directory.counts);
 assert.ok(directory.members.every(m=>m.email&&m.mobile&&m.regId));
 assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM user_credentials').first()).n,13);
 await db.prepare("UPDATE vendors SET is_open=1 WHERE id='vendor-3'").run();
 assert.equal((await request('/api/home',{cookie:a})).data.pulse.food,11);
 await db.prepare("UPDATE vendors SET is_open=0 WHERE id='vendor-3'").run();
 const switched=await request('/api/auth',{cookie:signed.cookie,method:'POST',body:{action:'set-password',currentPassword:'QuadDemo!2026',password:'NewDemo!Pass2026'}});
 await request('/api/me',{cookie:signed.cookie,status:401});
 await passwordLogin('student0@demo.campus.ac.in','QuadDemo!2026',401);
 await passwordLogin('student0@demo.campus.ac.in','NewDemo!Pass2026');
 await request('/api/auth',{cookie:switched.cookie,method:'POST',status:401,body:{action:'set-password',currentPassword:'incorrect',password:'AnotherPassword!2026'}});
 await request('/api/auth',{cookie:switched.cookie,method:'POST',body:{action:'set-password',currentPassword:'NewDemo!Pass2026',password:'QuadDemo!2026'}});
 for(let i=0;i<10;i++)await passwordLogin('unknown@demo.campus.ac.in','incorrect',401);
 await passwordLogin('unknown@demo.campus.ac.in','incorrect',429);
 a=await login(demos[0].id);
 console.log('Password login/change, hash records, session revocation, throttling and live directory counts passed');

 for(const path of ['/api/me','/api/home','/api/buddies','/api/buddies?interest=Coding','/api/chats','/api/events','/api/vendors','/api/telemetry','/api/matches'])await request(path,{cookie:a});
 console.log('Core API reads passed');
 for(const kind of ['beacons','pins','practice','games','equipment','posts','bounties','barters','market','food','culture','flash','schedules','lectures','projects','chai','duel_questions','quiet_spots','quests','flashcards','rooms','destinations','guardian_routes','leaderboard'])await request('/api/community?kind='+kind,{cookie:a});
 await request('/api/focus',{cookie:a,method:'POST',body:{action:'start',kind:'solo',duration:25}});
 await request('/api/focus',{cookie:a,method:'POST',body:{action:'pause',kind:'solo'}});
 assert.equal((await request('/api/focus?kind=solo',{cookie:a})).data.session.status,'paused');
 assert.equal((await request('/api/focus?kind=solo',{cookie:b})).data.session,null);
 await request('/api/focus',{cookie:a,method:'POST',body:{action:'resume',kind:'solo'}});
 const lectures=(await request('/api/community?kind=lectures',{cookie:a})).data.items;
 await request('/api/community',{cookie:a,method:'POST',body:{action:'note',id:lectures[0].id,text:'A persistent lecture note'}});
 assert.ok((await request('/api/community?kind=lectures',{cookie:b})).data.items.find(x=>x.id===lectures[0].id).notes.some(x=>x.text==='A persistent lecture note'));
 console.log('Catalog reads, shared lecture notes and private focus timer controls passed');

 await request('/api/community?kind=pins',{status:401});
 const pin=(await request('/api/community',{cookie:a,method:'POST',status:201,body:{action:'create',kind:'pins',data:{title:'Database persistence test',locationName:'Library',x:42,y:14,category:'study',duration:45}}})).data.item;
 const others=(await request('/api/community?kind=pins',{cookie:b})).data.items;assert.ok(others.some(p=>p.id===pin.id));
 await request('/api/community',{cookie:b,method:'POST',body:{action:'join',id:pin.id}});
 await request('/api/community',{cookie:b,method:'POST',body:{action:'join',id:pin.id}});
 const joined=(await request('/api/community?kind=pins',{cookie:a})).data.items.find(p=>p.id===pin.id);assert.equal(joined.attendees.length,2);
 await request('/api/community',{cookie:b,method:'POST',status:403,body:{action:'delete',id:pin.id}});
 assert.ok((await request('/api/home',{cookie:a})).data.announcements.some(n=>n.title==='Campus activity'));
 console.log('Cross-account pins, idempotent join, owner notifications and permissions passed');
 await request('/api/preferences?key=goals',{status:401});
 await request('/api/preferences',{cookie:a,method:'PUT',body:{key:'goals',value:[{id:'test',done:true}],version:-1}});
 assert.equal((await request('/api/preferences?key=goals',{cookie:b})).data.value,null);
 await request('/api/preferences',{cookie:a,method:'PUT',status:409,body:{key:'goals',value:[],version:-1}});
 const market=(await request('/api/community',{cookie:a,method:'POST',status:201,body:{action:'create',kind:'market',data:{title:'One calculator',price:200,category:'Academic Gear'}}})).data.item;
 const responses=await Promise.all([b,c].map(cookie=>mf.dispatchFetch('http://localhost/api/community',{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify({action:'reserve',id:market.id})})));
 assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);for(const r of responses)await r.text();
 console.log('Private preferences, stale-write rejection and concurrent reservations passed');
 const chat=(await request('/api/chats',{cookie:a,method:'POST',status:201,body:{action:'initiate',receiverId:demos[1].id,message:'Persistence test'}})).data;
 console.log('chat response fields',Object.keys(chat));
 const sessionId=chat.sessionId||chat.session?.id;
 assert.ok(sessionId);
 await request('/api/chats',{cookie:b,method:'POST',body:{action:'respond',sessionId,response:'accept'}});
 await request('/api/chats',{cookie:a,method:'POST',body:{action:'message',sessionId,kind:'text',body:'Saved permanently'}});
 const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aU1sAAAAASUVORK5CYII=';
 await request('/api/chats',{cookie:a,method:'POST',body:{action:'message',sessionId,kind:'image',body:png}});
 const detail=(await request('/api/chats?id='+sessionId,{cookie:b})).data;
 const media=detail.messages.find(m=>m.kind==='image').body;assert.ok(media.startsWith('/api/media/'));
 let r=await mf.dispatchFetch('http://localhost'+media,{headers:{Cookie:b}});assert.equal(r.status,200);assert.ok((await r.arrayBuffer()).byteLength>0);
 await request(media,{cookie:c,status:403});
 console.log('Chat persistence and private object-storage media passed');
 const routes=(await request('/api/community?kind=guardian_routes',{cookie:a})).data.items;
 const walk=(await request('/api/guardian',{cookie:a,method:'POST',body:{action:'start',routeId:routes[0].id}})).data.session;
 await request('/api/guardian',{cookie:b,method:'POST',status:404,body:{action:'arrived',id:walk.id}});
 await request('/api/guardian',{cookie:a,method:'POST',body:{action:'arrived',id:walk.id}});
 const checkCareerPersistence=await testCareer(request,db,a,b,c);
 await mf.dispose();mf=new Miniflare(options);
 await checkCareerPersistence();
 await passwordLogin('student0@demo.campus.ac.in','QuadDemo!2026');
 assert.ok((await request('/api/community?kind=pins',{cookie:a})).data.items.some(p=>p.id===pin.id));
 assert.equal((await request('/api/preferences?key=goals',{cookie:a})).data.value[0].done,true);
 assert.equal((await request('/api/guardian',{cookie:a})).data.session.status,'arrived');
 assert.ok((await request('/api/chats?id='+sessionId,{cookie:b})).data.messages.some(m=>m.body==='Saved permanently'));
 r=await mf.dispatchFetch('http://localhost'+media,{headers:{Cookie:b}});assert.equal(r.status,200);await r.arrayBuffer();
 console.log('Worker restart: session, shared pin, private progress, walk, messages and media persisted.');
 console.log('ALL DATABASE TESTS PASSED');
 if(process.env.BROWSER_QA==='1'){
  const {createRequire}=await import('node:module');const {chromium}=createRequire(import.meta.url)('playwright');
  const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||undefined,args:['--no-sandbox']});
  try{const context=await browser.newContext({viewport:{width:390,height:844}});const base=(await mf.ready).origin;
   await context.addCookies([{name:'quad_session',value:a.split('=')[1],url:base}]);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
   page.on('console',msg=>{if(msg.type()==='error')console.log('Browser console:',msg.text().slice(0,400));});page.on('response',r=>{if(r.status()>=400)console.log('Browser HTTP:',r.status(),r.url());});await page.goto(base);await page.waitForTimeout(2000);console.log('Browser initial:',(await page.locator('body').innerText()).slice(0,1000),errors);await page.getByRole('button',{name:'Buddies',exact:true}).waitFor({timeout:30000});await page.getByRole('button',{name:'Buddies',exact:true}).click();
   console.log('Buddies buttons',await page.getByRole('button').allTextContents());
   for(const label of ['Exchange','Pulse','Academics','People']){const button=page.getByRole('button',{name:new RegExp(label)}).first();await button.click();await page.waitForTimeout(250);console.log('Opened',label);}
   await page.getByRole('button',{name:'Campus',exact:true}).click();await page.waitForTimeout(300);
   await page.getByRole('button',{name:'Chats',exact:true}).click();await page.waitForTimeout(300);
   await page.getByRole('button',{name:'Home',exact:true}).click();await page.waitForTimeout(300);
   await testCareerBrowser(context,page,base);
   await page.getByRole('button',{name:'View all members & account details'}).click();
   await page.getByText('13 members including you',{exact:false}).waitFor();
   await page.getByRole('button',{name:'Close member directory'}).click();
   const loginContext=await browser.newContext({viewport:{width:390,height:844}});const loginPage=await loginContext.newPage();
   await loginPage.goto(base+'/login');await loginPage.locator('input[type=email]').fill('student0@demo.campus.ac.in');
   await loginPage.getByLabel('Password',{exact:true}).fill('QuadDemo!2026');
   await loginPage.getByRole('button',{name:'Sign in with password'}).click();
   await loginPage.getByRole('button',{name:'Home',exact:true}).waitFor({timeout:30000});
   await loginContext.close();
   assert.deepEqual(errors,[]);console.log('Browser password sign-in, member directory and navigation passed.');
  }finally{await browser.close();}
 }
}finally{await mf.dispose();}
