"use client";
import {useState} from 'react';
import {useCareer} from '@/lib/use-career';
import type {CareerProfile,CareerData} from '@/lib/career-types';
import {IconSparkles,IconChevronRight} from '@/components/icons';

export function CareerProfileEditor({data,busy,onSave,mode='skills'}:{data:CareerData;busy:boolean;onSave:(profile:CareerProfile)=>Promise<unknown>;mode?:'skills'|'roadmap'}){
 const [draft,setDraft]=useState(data.profile),[skills,setSkills]=useState(data.profile.skills.join(', '));
 const set=(key:keyof CareerProfile,value:string)=>setDraft(d=>({...d,[key]:value}));
 return <form onSubmit={async e=>{e.preventDefault();await onSave({...draft,skills:skills.split(',').map(s=>s.trim()).filter(Boolean)});}} className="career-card space-y-3">
 <h3 className="font-bold text-slate-800">{mode==='skills'?'Your skills & target role':'Your academic roadmap'}</h3>
 <p className="text-xs text-slate-500">Self-reported and private. Nothing is synced to the university portal.</p>
 {mode==='skills'?<><label className="career-label">Skills, separated by commas<input className="career-input" value={skills} onChange={e=>setSkills(e.target.value)} placeholder="JavaScript, React, Python" maxLength={1800}/></label><label className="career-label">Target role<input className="career-input" value={draft.targetRole} onChange={e=>set('targetRole',e.target.value)} placeholder="Full-stack developer intern" maxLength={120}/></label></>:<>
 <div className="grid grid-cols-2 gap-3">{([['term','Semester / term','text'],['cgpa','Current CGPA (0–10)','number'],['cgpaGoal','CGPA goal (0–10)','number'],['attendance','Attendance (%)','number'],['internshipHours','Internship hours completed','number'],['internshipGoal','Internship hours goal','number']] as const).map(([key,label,type])=><label key={key} className="career-label">{label}<input className="career-input" type={type} min={0} step="any" max={key==='attendance'?100:key==='cgpa'||key==='cgpaGoal'?10:undefined} value={draft[key]} onChange={e=>set(key,e.target.value)} /></label>)}</div>
 <label className="career-label">Certification goals<textarea aria-label="Certification goals" className="career-input" value={draft.certifications} onChange={e=>set('certifications',e.target.value)} maxLength={500}/></label></>}
 <button disabled={busy} className="career-primary">{busy?'Saving…':'Save '+(mode==='skills'?'skills':'roadmap')}</button>
 </form>;
}
export function CareerSkillBoostHub(){
 const {data,error,busy,reload,mutate}=useCareer();const [tab,setTab]=useState('tracks'),[category,setCategory]=useState('All'),[target,setTarget]=useState(''),[answer,setAnswer]=useState(''),[resume,setResume]=useState<string|null>(null);
 const saveProfile=(profile:CareerProfile)=>mutate({action:'profile',profile,version:data!.version});
 const questions=data?.questions??[],opportunities=data?.opportunities??[];
 const targetId=target||(tab==='interview'?questions[0]?.id:opportunities[0]?.id)||'';
 const lastAttempt=data?.attempts.find(a=>a.kind===(tab==='interview'?'interview':'resume-check')&&a.targetId===targetId);
 return <section className="space-y-4">
 <div className="flex items-center gap-3"><span className="rounded-2xl bg-indigo-100 p-3 text-indigo-700"><IconSparkles/></span><div><h2 className="font-display text-xl font-bold text-slate-900">Career & Skills</h2><p className="text-xs text-slate-500">Build skills. Keep your progress. Prepare for your next step.</p></div></div>
 <div className="career-tabs">{[['tracks','Skill tracks'],['roadmap','Roadmap'],['resume','Resume check'],['interview','Interview practice']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setTarget('');setAnswer('');}} className={tab===id?'career-tab active':'career-tab'}>{label}</button>)}</div>
 {error&&<p className="career-error" role="alert">{error} <button onClick={()=>reload().catch(()=>{})} className="underline">Reload saved data</button></p>}
 {!data?<p role="status" className="career-card">Loading your career workspace…</p>:<>
 {tab==='tracks'&&<><CareerProfileEditor key={'skills-'+data.version} data={data} busy={busy} onSave={saveProfile}/>
 <div className="flex flex-wrap gap-2">{['All',...new Set(data.tracks.map(t=>t.category))].map(c=><button className={category===c?'career-chip active':'career-chip'} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 {data.tracks.filter(t=>category==='All'||t.category===category).map(track=><details key={track.id} className="career-card group"><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-bold uppercase text-indigo-600">{track.category} · {track.level}</p><h3 className="mt-1 font-bold text-slate-900">{track.title}</h3></div><IconChevronRight className="shrink-0 group-open:rotate-90"/></div><p className="mt-2 text-xs text-slate-500">{track.estimatedHours} estimated hours · {track.completed.length}/{track.modules.length} modules</p><progress className="mt-3 h-2 w-full accent-emerald-500" value={track.completed.length} max={track.modules.length}/></summary>
 <p className="my-3 text-xs text-slate-500">Suggested learning plan. Completion is self-reported; no academic credit is awarded here.</p>
 {!track.enrolled?<button className="career-primary" disabled={busy} onClick={()=>mutate({action:'progress',id:track.id,completed:[],version:track.version})}>Start track</button>:<div className="space-y-2">{track.modules.map((module,i)=><label className="flex items-start gap-2 rounded-xl bg-slate-50 p-3 text-xs" key={module}><input type="checkbox" className="mt-0.5 accent-emerald-600" checked={track.completed.includes(i)} disabled={busy} onChange={e=>mutate({action:'progress',id:track.id,completed:e.target.checked?[...track.completed,i]:track.completed.filter(n=>n!==i),version:track.version})}/>{module}</label>)}</div>}
 <p className="mt-3 text-xs text-indigo-700">Skills: {track.skills.join(' · ')}</p></details>)}</>}
 {tab==='roadmap'&&<><CareerProfileEditor key={'roadmap-'+data.version} mode="roadmap" data={data} busy={busy} onSave={saveProfile}/><div className="grid grid-cols-2 gap-3"><div className="career-card bg-indigo-50"><p className="text-xs text-slate-500">CGPA / goal</p><p className="mt-2 text-xl font-bold">{data.profile.cgpa||'—'} / {data.profile.cgpaGoal||'—'}</p></div><div className="career-card bg-amber-50"><p className="text-xs text-slate-500">Internship hours / goal</p><p className="mt-2 text-xl font-bold">{data.profile.internshipHours||'—'} / {data.profile.internshipGoal||'—'}</p></div></div><p className="text-xs text-slate-500">Check your actual attendance and credit requirements with your department. No vouchers or enrollment claims are generated.</p></>}
 {tab==='resume'&&<div className="career-card space-y-3"><h3 className="font-bold">Resume keyword alignment</h3><p className="text-xs text-slate-500">Compare your text with an opportunity’s required skills. This is a transparent keyword check, not a recruiter ATS score.</p><label className="career-label">Target opportunity<select aria-label="Target opportunity" className="career-input" value={targetId} onChange={e=>setTarget(e.target.value)}>{opportunities.map(o=><option value={o.id} key={o.id}>{o.title}</option>)}</select></label><label className="career-label">Your resume text<textarea aria-label="Your resume text" rows={8} className="career-input" value={resume??data.profile.resume} onChange={e=>setResume(e.target.value)} maxLength={12000} placeholder="Paste your experience, projects and skills. Include only claims you can explain."/></label><div className="flex flex-wrap gap-2"><button className="career-primary" disabled={busy} onClick={()=>mutate({action:'resume-check',id:targetId,answer:resume??data.profile.resume})}>Check keywords</button><button className="career-secondary" disabled={busy} onClick={()=>saveProfile({...data.profile,resume:resume??data.profile.resume})}>Save resume draft</button><a className="career-secondary" href="/resume" target="_blank" rel="noopener noreferrer">Print / save PDF</a></div><p className="text-xs text-slate-500">The printable resume uses your last saved draft.</p></div>}
 {tab==='interview'&&<div className="career-card space-y-3"><h3 className="font-bold">Interview practice</h3><label className="career-label">Question<select aria-label="Question" className="career-input" value={targetId} onChange={e=>{setTarget(e.target.value);setAnswer('');}}>{questions.map((q,i)=><option value={q.id} key={q.id}>Question {i+1}</option>)}</select></label><p className="rounded-2xl bg-purple-50 p-4 text-sm font-bold text-purple-900">{questions.find(q=>q.id===targetId)?.title}</p><label className="career-label">Your answer<textarea aria-label="Your answer" className="career-input" rows={6} maxLength={12000} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Explain your reasoning and give a concrete example."/></label><button disabled={busy} className="career-primary" onClick={()=>mutate({action:'interview',id:targetId,answer})}>{busy?'Saving…':'Save & review answer'}</button></div>}
 {['resume','interview'].includes(tab)&&lastAttempt&&<div className="career-card bg-emerald-50 space-y-2" role="status"><h3 className="font-bold">Latest saved check · {lastAttempt.feedback.score}% keyword coverage</h3><p className="text-xs">Covered: {lastAttempt.feedback.matched.join(', ')||'No target keywords found.'}</p><p className="text-xs">Review: {lastAttempt.feedback.missing.join(', ')||'All target keywords mentioned.'}</p><p className="text-xs text-slate-500">{lastAttempt.feedback.note}</p><details><summary className="text-xs font-bold cursor-pointer">Saved answer</summary><p className="mt-2 whitespace-pre-wrap break-words text-xs">{lastAttempt.answer}</p></details></div>}
 </>}
 </section>;
}
