"use client";
import {useEffect,useState} from 'react';
import {api,fmtEventDate} from '@/lib/client';
import type {HomeData,VendorListItem} from '@/lib/types';
import type {Tab} from '@/app/page';
import {IconUsers,IconCoffee,IconSparkles,IconChevronRight} from '@/components/icons';
export function DashboardMetrics({data,onNavigate}:{data:HomeData|null;onNavigate:(tab:Tab)=>void}){
 const [tab,setTab]=useState('vibe'),[vendors,setVendors]=useState<VendorListItem[]>([]),[error,setError]=useState('');
 useEffect(()=>{if(tab!=='corners')return;let active=true;api<{vendors:VendorListItem[]}>('/api/vendors').then(d=>{if(active){setVendors(d.vendors);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[tab]);
 return <section className="space-y-4"><div className="career-tabs">{[['vibe','🌿 Warm Vibe'],['rhythm','📈 Rhythm'],['corners','☕ Cozy Corners']].map(([id,label])=><button key={id} className={tab===id?'career-tab active':'career-tab'} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='vibe'&&<><div className="grid grid-cols-3 gap-2 sm:gap-3">{[{value:data?.pulse.buddies,label:'Buddies to meet',icon:IconUsers,color:'bg-indigo-50 text-indigo-700',tab:'buddies' as Tab},{value:data?.pulse.food,label:'Cafés open',icon:IconCoffee,color:'bg-emerald-50 text-emerald-700',tab:'campus' as Tab},{value:data?.pulse.events,label:'Gatherings',icon:IconSparkles,color:'bg-amber-50 text-amber-700',tab:'buddies' as Tab}].map(c=><button key={c.label} className={'rounded-2xl p-3 sm:p-4 text-left '+c.color} onClick={()=>onNavigate(c.tab)}><c.icon size={22}/><p className="mt-4 text-3xl font-bold text-slate-800">{c.value??'—'}</p><p className="mt-1 text-[11px] font-semibold text-slate-600">{c.label}</p></button>)}</div><div className="career-card flex items-center gap-3"><span className="rounded-full bg-emerald-100 p-3 text-emerald-700"><IconCoffee/></span><div className="flex-1"><p className="text-sm font-bold">Campus cafés</p><p className="text-xs text-slate-500">{data?`${data.pulse.food} of ${data.pulse.vendors} marked open`:'Loading stored status…'}</p><progress className="mt-2 h-2 w-full accent-emerald-500" max={data?.pulse.vendors||1} value={data?.pulse.food??0}/></div></div></>}
 {tab==='rhythm'&&<div className="career-card space-y-3"><h3 className="font-bold">Your campus calendar</h3><p className="text-xs text-slate-500">Upcoming listings from the event directory.</p>{data?.trending.map(e=><button key={e.id} className="flex w-full items-center justify-between gap-2 rounded-xl bg-slate-50 p-3 text-left" onClick={()=>onNavigate('buddies')}><div><p className="text-xs font-bold">{e.title}</p><p className="mt-1 text-[11px] text-slate-500">{fmtEventDate(e.startsAt)} · {e.location}</p></div><IconChevronRight size={16}/></button>)}{data&&!data.trending.length&&<p className="text-sm">No events listed yet.</p>}</div>}
 {tab==='corners'&&<div className="grid gap-3 sm:grid-cols-2">{error&&<p role="alert" className="career-error">{error}</p>}{vendors.slice(0,6).map(v=><button className="career-card text-left" key={v.id} onClick={()=>onNavigate('campus')}><p className="font-bold text-sm">{v.name}</p><p className="mt-1 text-xs text-slate-500">{v.isOpen?'Marked open':'Marked closed'} · {v.topDish}</p></button>)}</div>}
 </section>;
}
