"use client";
import {useState} from 'react';
import {api} from '@/lib/client';
import {useApp} from '@/app/page';
import {useCareer} from '@/lib/use-career';
import type {Opportunity} from '@/lib/career-types';
import {Modal} from '@/components/ui';
import {CareerSkillBoostHub} from '@/components/CareerSkillBoostHub';
import {IconBookmark,IconSparkles,IconChevronRight} from '@/components/icons';
type Applicant={userId:string;fullName:string;course:string;email:string;note:string;status:string};
export function PersonalizedOpportunities(){
 const {me,toast}=useApp();const {data,error,busy,reload,mutate}=useCareer();
 const [filter,setFilter]=useState('For You'),[search,setSearch]=useState(''),[layout,setLayout]=useState('reel'),[selectedId,setSelectedId]=useState<string|null>(null),[note,setNote]=useState(''),[consent,setConsent]=useState(false),[careerOpen,setCareerOpen]=useState(false),[createOpen,setCreateOpen]=useState(false),[applicants,setApplicants]=useState<Applicant[]|null>(null),[appError,setAppError]=useState('');
 const selected=data?.opportunities.find(o=>o.id===selectedId);
 const list=(data?.opportunities??[]).filter(o=>(filter==='Saved'?o.saved:filter==='Applied'?!!o.application:filter==='Freshers'?o.category==='Freshers':true)&&[o.title,o.company,...o.requirements].join(' ').toLowerCase().includes(search.toLowerCase()));
 async function loadApplicants(id:string){setAppError('');try{setApplicants((await api<{applicants:Applicant[]}>('/api/career?applicants='+encodeURIComponent(id))).applicants);}catch(e){setAppError(e instanceof Error?e.message:'Could not load applicants.');}}
 const open=(o:Opportunity)=>{setSelectedId(o.id);setNote('');setConsent(false);setApplicants(null);setAppError('');};
 return <section className="space-y-3">
 <div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-lg font-bold text-slate-900">Opportunities for you</h2><p className="text-xs text-slate-500">Based on the skills you choose to share.</p></div><button className="career-chip" onClick={()=>setCareerOpen(true)}><IconSparkles size={14}/> Career tools</button></div>
 <div className="career-tabs">{['For You','Freshers','All Campus','Saved','Applied'].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'career-tab active':'career-tab'}>{f}</button>)}</div>
 <div className="flex gap-2"><input aria-label="Search opportunities" className="career-input min-w-0 flex-1" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search roles, companies or skills"/><button aria-label="Toggle opportunity layout" onClick={()=>setLayout(layout==='reel'?'stack':'reel')} className="career-secondary">{layout==='reel'?'☷ List':'▥ Cards'}</button></div>
 {error&&<p className="career-error" role="alert">{error} <button className="underline" onClick={()=>reload().catch(()=>{})}>Reload</button></p>}
 {!data?<p className="career-card">Loading opportunities…</p>:<>
 {!data.profile.skills.length&&<p className="rounded-xl bg-indigo-50 p-3 text-xs text-indigo-800">Add your skills in Career tools to calculate matches. No skills are assumed.</p>}
 <div className={layout==='reel'?'opportunity-reel':'grid gap-3 sm:grid-cols-2'}>{list.map((o,i)=><article key={o.id} className={'career-card opportunity-card '+['bg-indigo-50/60','bg-orange-50/60','bg-emerald-50/60'][i%3]}>
 <div className="flex items-start justify-between gap-2"><span className="text-[10px] font-bold uppercase text-slate-500">{o.sample?'Sample opportunity':o.closed?'Closed':'Campus listing'}</span><button aria-label={(o.saved?'Unsave ':'Save ')+o.title} aria-pressed={o.saved} disabled={busy} onClick={()=>mutate({action:'bookmark',id:o.id,saved:!o.saved})} className={'rounded-lg p-2 '+(o.saved?'bg-indigo-100 text-indigo-700':'text-slate-400')}><IconBookmark size={17}/></button></div>
 <h3 className="mt-2 font-bold text-slate-900">{o.title}</h3><p className="mt-1 text-xs text-slate-500">{o.company}</p><p className="mt-3 text-xs font-bold text-slate-700">{o.stipend}</p><p className="mt-2 text-xs text-emerald-800">{o.match===null?'Requirements not specified':o.match+'% skill overlap'} · {o.matched.length}/{o.requirements.length} matched</p>
 <p className="mt-1 text-[11px] text-slate-500">{o.matched.length?'Matches '+o.matched.join(', '):'No required skills matched yet'}</p><button className="career-secondary mt-4 w-full justify-between" onClick={()=>open(o)}>{o.application?'Application: '+o.application:'View opportunity'}<IconChevronRight size={14}/></button>
 </article>)}</div>{!list.length&&<p className="career-card text-sm text-slate-500">No opportunities in this view.</p>}
 </>}
 <button onClick={()=>setCreateOpen(true)} className="career-secondary w-full">+ Post a campus opportunity</button>
 <Modal open={careerOpen} onClose={()=>{setCareerOpen(false);reload().catch(()=>{});}}><button aria-label="Close career tools" className="float-right career-chip" onClick={()=>{setCareerOpen(false);reload().catch(()=>{});}}>✕</button><div className="max-h-[75dvh] overflow-y-auto clear-both pt-3">{careerOpen&&<CareerSkillBoostHub/>}</div></Modal>
 <Modal open={!!selected} onClose={()=>setSelectedId(null)}>{selected&&<div className="max-h-[75dvh] overflow-y-auto space-y-3"><button aria-label="Close opportunity" className="float-right career-chip" onClick={()=>setSelectedId(null)}>✕</button><h3 className="pr-10 font-display text-xl font-bold">{selected.title}</h3><p className="text-sm text-slate-500">{selected.company} · {selected.type}</p><p className="text-sm">{selected.description}</p><p className="text-xs font-bold">Required: {selected.requirements.join(', ')}</p>{selected.sample&&<p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900">Demo listing. Applications are saved inside this app; no employer is contacted.</p>}
 {error&&<p role="alert" className="career-error">{error}</p>}
 {selected.ownerId===me?.user.id?<><button className="career-primary" onClick={()=>loadApplicants(selected.id)}>View applicants</button><button disabled={busy||selected.closed} className="career-secondary" onClick={()=>mutate({action:'close-opportunity',id:selected.id})}>{selected.closed?'Listing closed':'Close listing'}</button>{appError&&<p role="alert">{appError}</p>}{applicants?.length===0&&<p className="text-sm">No applications yet.</p>}{applicants?.map(a=><article key={a.userId} className="career-card space-y-2 text-xs"><p className="font-bold">{a.fullName} · {a.course}</p><p className="break-all">{a.email}</p><p className="whitespace-pre-wrap">{a.note}</p><select aria-label={'Application status for '+a.fullName} className="career-input" value={a.status} disabled={busy} onChange={async e=>{if(await mutate({action:'review-application',id:selected.id,userId:a.userId,status:e.target.value}))await loadApplicants(selected.id);}}>{['Pending','Accepted','Declined'].map(s=><option key={s}>{s}</option>)}</select></article>)}</>:selected.application?<p role="status" className="career-card bg-emerald-50">Saved application · {selected.application}</p>:selected.closed?<p>Applications are closed.</p>:<form className="space-y-3" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'apply',id:selected.id,note,consent}))toast('Application saved in the app.','ok');}}><label className="career-label">Application note<textarea className="career-input" rows={4} minLength={10} maxLength={4000} required value={note} onChange={e=>setNote(e.target.value)} placeholder="Introduce yourself and describe your relevant work."/></label><label className="flex items-start gap-2 text-xs"><input type="checkbox" checked={consent} required onChange={e=>setConsent(e.target.checked)}/>Share my name, course, email and this note with the listing’s poster.</label><button className="career-primary" disabled={busy}>{busy?'Saving…':'Submit application'}</button></form>}</div>}</Modal>
 <Modal open={createOpen} onClose={()=>setCreateOpen(false)}><div className="max-h-[75dvh] overflow-y-auto"><button className="float-right career-chip" aria-label="Close new opportunity" onClick={()=>setCreateOpen(false)}>✕</button><h3 className="font-bold text-lg mb-4">Post an opportunity</h3>{error&&<p className="career-error" role="alert">{error}</p>}<form className="space-y-3" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries());if(await mutate({...body,action:'create-opportunity',requirements:String(body.requirements).split(',').map(s=>s.trim()).filter(Boolean)})){setCreateOpen(false);toast('Opportunity posted.','ok');}}}>{[['title','Role title'],['company','Team or organization'],['type','Type (internship, gig, project…)'],['stipend','Stipend / reward'],['requirements','Required skills (comma separated)']].map(([name,label])=><label key={name} className="career-label">{label}<input name={name} className="career-input" required maxLength={name==='requirements'?900:120}/></label>)}<label className="career-label">Audience<select name="category" className="career-input"><option>All Campus</option><option>Freshers</option></select></label><label className="career-label">Description<textarea name="description" required className="career-input" maxLength={2000}/></label><button className="career-primary" disabled={busy}>{busy?'Posting…':'Post opportunity'}</button></form></div></Modal>
 </section>;
}
