"use client";
import {useCallback,useEffect,useState} from 'react';
import {useApp} from '@/app/page';
import {api} from '@/lib/client';
import {Modal} from '@/components/ui';
import type {SkillBeacon} from '@/lib/career-types';
export const beaconKinds=[['skill','💡 Skills'],['bounty','💰 Bounties'],['hackathon','🚀 Teams'],['study','📚 Study']] as const;
const blocks=[{name:'Current map pin',x:50,y:40},{name:'Central Library',x:43,y:22},{name:'Block 34 · Design & IT',x:21,y:34},{name:'Block 32 · Engineering',x:32,y:38},{name:'Unipolis',x:68,y:55},{name:'Block 14 · Classrooms',x:55,y:68},{name:'Uni-Mall',x:74,y:36}];
export function useSkillBeacons(){
 const [beacons,setBeacons]=useState<SkillBeacon[]>([]),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<string|null>(null);
 const reload=useCallback(async()=>{const res=await api<{beacons:SkillBeacon[]}>('/api/skill-beacons');setBeacons(res.beacons);setError('');},[]);
 useEffect(()=>{let active=true;const refresh=()=>api<{beacons:SkillBeacon[]}>('/api/skill-beacons').then(r=>{if(active){setBeacons(r.beacons);setError('');}}).catch(e=>{if(active)setError(e.message);});void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},30000);return()=>{active=false;clearInterval(timer);};},[]);
 return {beacons,error,filter,setFilter,selected,setSelected,reload};
}
export function SkillBeaconTools({state,you,onNavigate}:{state:ReturnType<typeof useSkillBeacons>;you:{x:number;y:number};onNavigate:(pos:{x:number;y:number;name:string})=>void}){
 const {me,openChat,toast}=useApp();const [creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[block,setBlock]=useState(0);
 const item=state.beacons.find(b=>b.id===state.selected),nearby=item?state.beacons.filter(b=>Math.round(b.x/5)===Math.round(item.x/5)&&Math.round(b.y/5)===Math.round(item.y/5)):[],visible=state.beacons.filter(b=>state.filter==='all'||b.kind===state.filter);
 async function action(body:Record<string,unknown>){setBusy(true);setError('');try{const result=await api<{id?:string}>('/api/skill-beacons',{method:'POST',body:JSON.stringify(body)});await state.reload();return result;}catch(e){setError(e instanceof Error?e.message:'Could not save.');return null;}finally{setBusy(false);}}
 return <section className="border-b border-slate-200 bg-white px-4 py-4 space-y-3"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Skill & opportunity pins</h2><p className="text-xs text-slate-500">Meet, help, study or build a team at a specific spot.</p></div><button className="career-primary shrink-0" onClick={()=>{setCreating(true);setError('');}}>+ Drop pin</button></div>
 <div className="flex flex-wrap gap-2">{[['all','All pins'],...beaconKinds].map(([id,label])=><button key={id} className={state.filter===id?'career-chip active':'career-chip'} onClick={()=>state.setFilter(id)}>{label}</button>)}</div>
 {state.error&&<p role="alert" className="career-error">{state.error} <button onClick={()=>state.reload().catch(()=>{})} className="underline">Retry</button></p>}
 {!visible.length?<p className="text-xs text-slate-500">No active pins in this view. Create one at your map pin or a campus block.</p>:<div className="flex gap-2 overflow-x-auto pb-1">{visible.map(b=><button key={b.id} className="career-card min-w-52 text-left" onClick={()=>{state.setSelected(b.id);setError('');}}><p className="text-xs font-bold">{b.title}</p><p className="mt-1 text-[11px] text-slate-500">{b.location}{b.room?' · '+b.room:''}</p><p className="mt-1 text-[11px] text-emerald-700">{b.members} joined · until {new Date(b.expiresAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p></button>)}</div>}
 <Modal open={creating} onClose={()=>setCreating(false)}><button aria-label="Close drop pin" className="float-right career-chip" onClick={()=>setCreating(false)}>✕</button><h3 className="font-bold text-xl mb-3">Drop a campus pin</h3>{error&&<p role="alert" className="career-error">{error}</p>}<form className="space-y-3" onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),body=Object.fromEntries(fd.entries());const position=block===0?you:blocks[block];const result=await action({...body,action:'create',x:Math.round(position.x),y:Math.round(position.y),location:blocks[block].name,duration:Number(body.duration)});if(result){setCreating(false);state.setSelected(result.id!);state.setFilter('all');toast('Pin saved and shown on the map.','ok');}}}>
 <label className="career-label">Type<select aria-label="Type" name="kind" className="career-input">{beaconKinds.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>
 <label className="career-label">Title<input name="title" className="career-input" required maxLength={150} placeholder="React code review / study partner…"/></label>
 <label className="career-label">Campus location<select aria-label="Campus location" className="career-input" value={block} onChange={e=>setBlock(Number(e.target.value))}>{blocks.map((b,i)=><option value={i} key={b.name}>{b.name}</option>)}</select></label>
 <div className="grid grid-cols-2 gap-3"><label className="career-label">Room / meeting point<input name="room" className="career-input" maxLength={150} placeholder="Room 204"/></label><label className="career-label">Duration (minutes)<input name="duration" className="career-input" type="number" min={15} max={1440} defaultValue={45} required/></label></div>
 <label className="career-label">Reward / offer (optional)<input name="reward" className="career-input" maxLength={150} placeholder="Peer help, notes exchange…"/></label><label className="career-label">Details<textarea aria-label="Details" name="description" className="career-input" maxLength={1500} rows={3}/></label><p className="text-xs text-slate-500">This is a schematic campus map. Confirm the exact location in chat. Rewards are arranged between members.</p><button disabled={busy} className="career-primary">{busy?'Saving…':'Place pin on map'}</button></form></Modal>
 <Modal open={!!item} onClose={()=>state.setSelected(null)}>{item&&<div className="space-y-3"><button aria-label="Close pin details" className="float-right career-chip" onClick={()=>state.setSelected(null)}>✕</button><h3 className="font-bold text-xl pr-10">{item.title}</h3>{nearby.length>1&&<label className="career-label">Pins at this location<select aria-label="Pins at this location" className="career-input" value={item.id} onChange={e=>{state.setSelected(e.target.value);setError('');}}>{nearby.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label>}<p className="text-sm text-slate-500">{item.creatorName} · {item.location}{item.room?' · '+item.room:''}</p><p className="text-sm whitespace-pre-wrap">{item.description}</p>{item.reward&&<p className="rounded-xl bg-amber-50 p-3 text-sm">Offer: {item.reward}</p>}<p className="text-xs text-slate-500">{item.members} joined · expires {new Date(item.expiresAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p>{error&&<p role="alert" className="career-error">{error}</p>}<div className="flex flex-wrap gap-2"><button className="career-secondary" onClick={()=>{onNavigate({x:item.x,y:item.y,name:item.title});state.setSelected(null);}}>Show meeting point</button>{item.userId===me?.user.id?<button disabled={busy} className="career-secondary" onClick={async()=>{if(await action({action:'delete',id:item.id}))state.setSelected(null);}}>Remove my pin</button>:<><button disabled={busy} className="career-primary" onClick={()=>action({action:item.joined?'leave':'join',id:item.id})}>{item.joined?'Leave meetup':'Join meetup'}</button><button disabled={busy} className="career-secondary" onClick={async()=>{setBusy(true);try{const chat=await api<{sessionId:string}>('/api/chats',{method:'POST',body:JSON.stringify({action:'initiate',receiverId:item.userId,message:'Hi! About your campus pin: '+item.title})});state.setSelected(null);openChat(chat.sessionId);}catch(e){setError(e instanceof Error?e.message:'Could not start chat.');}finally{setBusy(false);}}}>Message creator</button></>}</div></div>}</Modal>
 </section>;
}
